const basicWords = [
  {
    id: '5e9f5ee35eb9e72bc21af4c8',
    group: 0,
    page: 2,
    word: 'alien',
    image: 'files/03_0041.jpg',
    audio: 'files/03_0041.mp3',
    audioMeaning: 'files/03_0041_meaning.mp3',
    audioExample: 'files/03_0041_example.mp3',
    textMeaning: 'An <i>alien</i> is a creature from a different world.',
    textExample: 'The <b>alien</b> came in peace.',
    transcription: '[éiljən]',
    textExampleTranslate: 'пришелец пришел с миром',
    textMeaningTranslate: 'Инопланетянин - это существо из другого мира',
    wordTranslate: 'инопланетянин',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4c9',
    group: 0,
    page: 2,
    word: 'among',
    image: 'files/03_0042.jpg',
    audio: 'files/03_0042.mp3',
    audioMeaning: 'files/03_0042_meaning.mp3',
    audioExample: 'files/03_0042_example.mp3',
    textMeaning: 'If you are <i>among</i> certain things, they are all around you.',
    textExample: 'There was a red apple <b>among</b> the green ones.',
    transcription: '[əmʌ̀ŋ]',
    textExampleTranslate: 'Среди зеленых было красное яблоко',
    textMeaningTranslate: 'Если вы среди определенных вещей, они все вокруг вас',
    wordTranslate: 'среди',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ca',
    group: 0,
    page: 2,
    word: 'chart',
    image: 'files/03_0043.jpg',
    audio: 'files/03_0043.mp3',
    audioMeaning: 'files/03_0043_meaning.mp3',
    audioExample: 'files/03_0043_example.mp3',
    textMeaning: 'A <i>chart</i> is a list of information.',
    textExample: 'We used a <b>chart</b> to see how we had improved.',
    transcription: '[tʃɑːrt]',
    textExampleTranslate: 'Мы использовали график, чтобы увидеть, как мы улучшили',
    textMeaningTranslate: 'Диаграмма - это список информации',
    wordTranslate: 'диаграмма',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4cb',
    group: 0,
    page: 2,
    word: 'cloud',
    image: 'files/03_0044.jpg',
    audio: 'files/03_0044.mp3',
    audioMeaning: 'files/03_0044_meaning.mp3',
    audioExample: 'files/03_0044_example.mp3',
    textMeaning: 'A <i>cloud</i> is a group of water drops in the sky.',
    textExample: 'The sky was filled with white <b>clouds</b>.',
    transcription: '[klaud]',
    textExampleTranslate: 'Небо было наполнено белыми облаками',
    textMeaningTranslate: 'Облако - это группа капель воды в небе',
    wordTranslate: 'облако',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4cc',
    group: 0,
    page: 2,
    word: 'describe',
    image: 'files/03_0045.jpg',
    audio: 'files/03_0045.mp3',
    audioMeaning: 'files/03_0045_meaning.mp3',
    audioExample: 'files/03_0045_example.mp3',
    textMeaning: 'To <i>describe</i> is to say or write what someone or something is like.',
    textExample: 'They <b>described</b> their tree as colorful, with gold ribbon and a star.',
    transcription: '[diskráib]',
    textExampleTranslate: 'Они описали свое дерево как красочное, с золотой лентой и звездой',
    textMeaningTranslate: 'Описать - это сказать или написать, на что похож кто-то или что-то',
    wordTranslate: 'описать',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4cd',
    group: 0,
    page: 2,
    word: 'ever',
    image: 'files/03_0046.jpg',
    audio: 'files/03_0046.mp3',
    audioMeaning: 'files/03_0046_meaning.mp3',
    audioExample: 'files/03_0046_example.mp3',
    textMeaning: '<i>Ever</i> means at any time.',
    textExample: 'Going skiing last winter was the most fun I’ve <b>ever</b> had.',
    transcription: '[évər]',
    textExampleTranslate: 'Кататься на лыжах прошлой зимой было самым веселым из всего, что я когда-либо ел',
    textMeaningTranslate: 'Всегда означает в любое время',
    wordTranslate: 'когда-либо',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ce',
    group: 0,
    page: 2,
    word: 'fail',
    image: 'files/03_0047.jpg',
    audio: 'files/03_0047.mp3',
    audioMeaning: 'files/03_0047_meaning.mp3',
    audioExample: 'files/03_0047_example.mp3',
    textMeaning: 'To <i>fail</i> means you do not succeed in what you try to do.',
    textExample: 'Since he <b>failed</b> to get the job, he was sad.',
    transcription: '[feil]',
    textExampleTranslate: 'Так как он не смог получить работу, ему было грустно',
    textMeaningTranslate: 'Неудача означает, что вам не удается то, что вы пытаетесь сделать',
    wordTranslate: 'потерпеть поражение',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4cf',
    group: 0,
    page: 2,
    word: 'grade',
    image: 'files/03_0048.jpg',
    audio: 'files/03_0048.mp3',
    audioMeaning: 'files/03_0048_meaning.mp3',
    audioExample: 'files/03_0048_example.mp3',
    textMeaning: 'A <i>grade</i> is a score or mark given to someone’s work.',
    textExample: 'I managed to get good <b>grades</b> on my report card.',
    transcription: '[greid]',
    textExampleTranslate: 'Мне удалось получить хорошие оценки на моем табеле',
    textMeaningTranslate: 'Оценка - это оценка или оценка, присвоенная чьей-либо работе',
    wordTranslate: 'класс',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d0',
    group: 0,
    page: 2,
    word: 'instead',
    image: 'files/03_0049.jpg',
    audio: 'files/03_0049.mp3',
    audioMeaning: 'files/03_0049_meaning.mp3',
    audioExample: 'files/03_0049_example.mp3',
    textMeaning: '<i>Instead</i> means in place of.',
    textExample: 'He ate the carrot <b>instead</b> of the ice cream.',
    transcription: '[instéd]',
    textExampleTranslate: 'Он съел морковку вместо мороженого',
    textMeaningTranslate: 'Вместо означает вместо',
    wordTranslate: 'вместо',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d1',
    group: 0,
    page: 2,
    word: 'library',
    image: 'files/03_0050.jpg',
    audio: 'files/03_0050.mp3',
    audioMeaning: 'files/03_0050_meaning.mp3',
    audioExample: 'files/03_0050_example.mp3',
    textMeaning: 'A <i>library</i> is a place where you go to read books.',
    textExample: 'The <b>library</b> at school is full of books.',
    transcription: '[láibrèri]',
    textExampleTranslate: 'Библиотека в школе полна книг',
    textMeaningTranslate: 'Библиотека - это место, куда вы ходите читать книги',
    wordTranslate: 'библиотека',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d2',
    group: 0,
    page: 2,
    word: 'photograph',
    image: 'files/03_0051.jpg',
    audio: 'files/03_0051.mp3',
    audioMeaning: 'files/03_0051_meaning.mp3',
    audioExample: 'files/03_0051_example.mp3',
    textMeaning: 'I like taking <i>photographs</i>.',
    textExample: 'I took this <b>photograph</b> with my cell phone.',
    transcription: '[fóutəgrӕf]',
    textExampleTranslate: 'Я сделал эту фотографию на свой мобильный',
    textMeaningTranslate: 'Мне нравится фотографировать',
    wordTranslate: 'фотография',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d3',
    group: 0,
    page: 2,
    word: 'planet',
    image: 'files/03_0052.jpg',
    audio: 'files/03_0052.mp3',
    audioMeaning: 'files/03_0052_meaning.mp3',
    audioExample: 'files/03_0052_example.mp3',
    textMeaning: 'A <i>planet</i> is a large round thing in space.',
    textExample: 'Saturn is the <b>planet</b> with the ring around it.',
    transcription: '[plǽnət]',
    textExampleTranslate: 'Сатурн - планета с кольцом вокруг него',
    textMeaningTranslate: 'Планета - это большая круглая вещь в космосе',
    wordTranslate: 'планета',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d4',
    group: 0,
    page: 2,
    word: 'report',
    image: 'files/03_0053.jpg',
    audio: 'files/03_0053.mp3',
    audioMeaning: 'files/03_0053_meaning.mp3',
    audioExample: 'files/03_0053_example.mp3',
    textMeaning: 'A <i>report</i> is something someone writes for school or work.',
    textExample: 'Karen had trouble writing her <b>report</b>.',
    transcription: '[ripɔ́ːrt]',
    textExampleTranslate: 'Карен не могла написать свой отчет',
    textMeaningTranslate: 'Отчет - это то, что кто-то пишет для школы или работы',
    wordTranslate: 'отчет',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d5',
    group: 0,
    page: 2,
    word: 'several',
    image: 'files/03_0054.jpg',
    audio: 'files/03_0054.mp3',
    audioMeaning: 'files/03_0054_meaning.mp3',
    audioExample: 'files/03_0054_example.mp3',
    textMeaning: '<i>Several</i> is more than two but not many.',
    textExample: 'He had to read <b>several</b> books for class.',
    transcription: '[sévərəl]',
    textExampleTranslate: 'Он должен был прочитать несколько книг для класса',
    textMeaningTranslate: 'Несколько больше двух, но не много',
    wordTranslate: 'несколько',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d6',
    group: 0,
    page: 2,
    word: 'shape',
    image: 'files/03_0055.jpg',
    audio: 'files/03_0055.mp3',
    audioMeaning: 'files/03_0055_meaning.mp3',
    audioExample: 'files/03_0055_example.mp3',
    textMeaning: 'An object’s <i>shape</i> is the arrangement of its sides and surfaces.',
    textExample: 'Even with your eyes closed you can feel the <b>shape</b> of it.',
    transcription: '[ʃeip]',
    textExampleTranslate: 'Даже с закрытыми глазами вы можете почувствовать его форму',
    textMeaningTranslate: 'Форма объекта - это расположение его сторон и поверхностей',
    wordTranslate: 'форма',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d7',
    group: 0,
    page: 2,
    word: 'solve',
    image: 'files/03_0056.jpg',
    audio: 'files/03_0056.mp3',
    audioMeaning: 'files/03_0056_meaning.mp3',
    audioExample: 'files/03_0056_example.mp3',
    textMeaning: 'To <i>solve</i> something is to find an answer to it.',
    textExample: 'All the students could easily <b>solve</b> the math problem.',
    transcription: '[sɑlv]',
    textExampleTranslate: 'Все ученики могли легко решить математическую задачу',
    textMeaningTranslate: 'Решить что-то - значит найти ответ',
    wordTranslate: 'решать',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d8',
    group: 0,
    page: 2,
    word: 'suddenly',
    image: 'files/03_0057.jpg',
    audio: 'files/03_0057.mp3',
    audioMeaning: 'files/03_0057_meaning.mp3',
    audioExample: 'files/03_0057_example.mp3',
    textMeaning: 'If something happens <i>suddenly</i>, it happens quickly and unexpectedly.',
    textExample: 'I was surprised when my friends <b>suddenly</b> shouted, “Happy birthday!”',
    transcription: '[sʌ́dnli]',
    textExampleTranslate: "Я был удивлен, когда мои друзья вдруг закричали: 'С днем рождения!'",
    textMeaningTranslate: 'Если что-то происходит внезапно, это происходит быстро и неожиданно',
    wordTranslate: 'вдруг, внезапно',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d9',
    group: 0,
    page: 2,
    word: 'suppose',
    image: 'files/03_0058.jpg',
    audio: 'files/03_0058.mp3',
    audioMeaning: 'files/03_0058_meaning.mp3',
    audioExample: 'files/03_0058_example.mp3',
    textMeaning: 'To <i>suppose</i> is to guess.',
    textExample: 'I <b>suppose</b> I should go home now.',
    transcription: '[səpóuz]',
    textExampleTranslate: 'Полагаю, мне пора домой',
    textMeaningTranslate: 'Предположить, значит угадать',
    wordTranslate: 'предположим',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4da',
    group: 0,
    page: 2,
    word: 'understand',
    image: 'files/03_0059.jpg',
    audio: 'files/03_0059.mp3',
    audioMeaning: 'files/03_0059_meaning.mp3',
    audioExample: 'files/03_0059_example.mp3',
    textMeaning: 'To <i>understand</i> something you need to know what it means.',
    textExample: 'Henry could not <b>understand</b> the message.',
    transcription: '[Λndərstǽnd]',
    textExampleTranslate: 'Генри не мог понять сообщение',
    textMeaningTranslate: 'Чтобы понять что-то, нужно знать, что это значит',
    wordTranslate: 'понимаю',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4db',
    group: 0,
    page: 2,
    word: 'view',
    image: 'files/03_0060.jpg',
    audio: 'files/03_0060.mp3',
    audioMeaning: 'files/03_0060_meaning.mp3',
    audioExample: 'files/03_0060_example.mp3',
    textMeaning: 'To <i>view</i> is to look at something.',
    textExample: 'Michael likes to <b>view</b> himself in the mirror.',
    transcription: '[vjuː]',
    textExampleTranslate: 'Михаилу нравится видеть себя в зеркале',
    textMeaningTranslate: 'Смотреть - значит смотреть на что-то',
    wordTranslate: 'посмотреть',
  },
];

const wrongWords = [
  {
    id: '5e9f5ee35eb9e72bc21af4dc',
    group: 0,
    page: 3,
    word: 'appropriate',
    image: 'files/04_0061.jpg',
    audio: 'files/04_0061.mp3',
    audioMeaning: 'files/04_0061_meaning.mp3',
    audioExample: 'files/04_0061_example.mp3',
    textMeaning: 'When a thing is <i>appropriate</i>, it is right or normal.',
    textExample: 'It’s <b>appropriate</b> to wear a suit when you go to the office.',
    transcription: '[əpróuprièit]',
    textExampleTranslate: 'Уместно носить костюм, когда вы идете в офис',
    textMeaningTranslate: 'Когда вещь уместна, она правильная или нормальная',
    wordTranslate: 'подходящее',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4dd',
    group: 0,
    page: 3,
    word: 'avoid',
    image: 'files/04_0062.jpg',
    audio: 'files/04_0062.mp3',
    audioMeaning: 'files/04_0062_meaning.mp3',
    audioExample: 'files/04_0062_example.mp3',
    textMeaning: 'To <i>avoid</i> something is to stay away from it.',
    textExample: '<b>Avoid</b> the broken bottle on the floor.',
    transcription: '[əvɔ́id]',
    textExampleTranslate: 'Избегайте разбитой бутылки на полу',
    textMeaningTranslate: 'Избегать чего-либо - значит держаться подальше от этого',
    wordTranslate: 'избегать',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4de',
    group: 0,
    page: 3,
    word: 'behave',
    image: 'files/04_0063.jpg',
    audio: 'files/04_0063.mp3',
    audioMeaning: 'files/04_0063_meaning.mp3',
    audioExample: 'files/04_0063_example.mp3',
    textMeaning: 'To <i>behave</i> is to act in a particular way, especially to be good.',
    textExample: 'She always <b>behaves</b> well when her father is around.',
    transcription: '[bihéiv]',
    textExampleTranslate: 'Она всегда ведет себя хорошо, когда ее отец рядом',
    textMeaningTranslate: 'Вести себя - значит действовать определенным образом, особенно быть хорошим',
    wordTranslate: 'вести себя',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4df',
    group: 0,
    page: 3,
    word: 'calm',
    image: 'files/04_0064.jpg',
    audio: 'files/04_0064.mp3',
    audioMeaning: 'files/04_0064_meaning.mp3',
    audioExample: 'files/04_0064_example.mp3',
    textMeaning: 'When someone is <i>calm</i>, they do not get excited or upset.',
    textExample: 'A nice warm bath makes me feel so <b>calm</b>.',
    transcription: '[kɑːm]',
    textExampleTranslate: 'Хорошая теплая ванна заставляет меня чувствовать себя так спокойно',
    textMeaningTranslate: 'Когда кто-то спокоен, он не волнуется и не расстраивается',
    wordTranslate: 'спокойный',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4e0',
    group: 0,
    page: 3,
    word: 'concern',
    image: 'files/04_0065.jpg',
    audio: 'files/04_0065.mp3',
    audioMeaning: 'files/04_0065_meaning.mp3',
    audioExample: 'files/04_0065_example.mp3',
    textMeaning: '<i>Concern</i> is a feeling of worry.',
    textExample: 'I was filled with <b>concern</b> after reading the newspaper.',
    transcription: '[kənsə́ːrn]',
    textExampleTranslate: 'Я был полон беспокойства после прочтения газеты',
    textMeaningTranslate: 'Беспокойство - это чувство беспокойства',
    wordTranslate: 'беспокойство',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4e1',
    group: 0,
    page: 3,
    word: 'content',
    image: 'files/04_0066.jpg',
    audio: 'files/04_0066.mp3',
    audioMeaning: 'files/04_0066_meaning.mp3',
    audioExample: 'files/04_0066_example.mp3',
    textMeaning: 'To be <i>content</i> is to be happy and not want more.',
    textExample: 'The baby looked very <b>content</b> sitting on the floor.',
    transcription: '[kəntént]',
    textExampleTranslate: 'Ребенок выглядел очень довольным, сидя на полу',
    textMeaningTranslate: 'Быть довольным значит быть счастливым и не хотеть большего',
    wordTranslate: 'содержание',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4e2',
    group: 0,
    page: 3,
    word: 'expect',
    image: 'files/04_0067.jpg',
    audio: 'files/04_0067.mp3',
    audioMeaning: 'files/04_0067_meaning.mp3',
    audioExample: 'files/04_0067_example.mp3',
    textMeaning: 'If you <i>expect</i> something to happen, you believe it will happen.',
    textExample: 'I <b>expect</b> the bus to be here very soon.',
    transcription: '[ikspékt]',
    textExampleTranslate: 'Я ожидаю, что автобус будет здесь очень скоро',
    textMeaningTranslate: 'Если вы ожидаете, что что-то случится, вы верите, что это произойдет',
    wordTranslate: 'ожидать',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4e3',
    group: 0,
    page: 3,
    word: 'frequently',
    image: 'files/04_0068.jpg',
    audio: 'files/04_0068.mp3',
    audioMeaning: 'files/04_0068_meaning.mp3',
    audioExample: 'files/04_0068_example.mp3',
    textMeaning: 'When something happens <i>frequently</i>, it happens often.',
    textExample: 'We meet <b>frequently</b>, either at the beginning or end of the week.',
    transcription: '[fríːkwəntli]',
    textExampleTranslate: 'Мы часто встречаемся, либо в начале, либо в конце недели',
    textMeaningTranslate: 'Когда что-то случается часто, это случается часто',
    wordTranslate: 'часто',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4e4',
    group: 0,
    page: 3,
    word: 'habit',
    image: 'files/04_0069.jpg',
    audio: 'files/04_0069.mp3',
    audioMeaning: 'files/04_0069_meaning.mp3',
    audioExample: 'files/04_0069_example.mp3',
    textMeaning: 'A <i>habit</i> is a thing that you do often.',
    textExample: 'Smoking is a bad <b>habit</b> that can kill you.',
    transcription: '[hǽbit]',
    textExampleTranslate: 'Курение - это вредная привычка, которая может тебя убить',
    textMeaningTranslate: 'Привычка - это то, что вы часто делаете',
    wordTranslate: 'привычка',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4e5',
    group: 0,
    page: 3,
    word: 'instruct',
    image: 'files/04_0070.jpg',
    audio: 'files/04_0070.mp3',
    audioMeaning: 'files/04_0070_meaning.mp3',
    audioExample: 'files/04_0070_example.mp3',
    textMeaning: 'To <i>instruct</i> is to teach.',
    textExample: 'My teacher <b>instructs</b> us in several subjects.',
    transcription: '[instrʌ́kt]',
    textExampleTranslate: 'Мой учитель учит нас нескольким предметам',
    textMeaningTranslate: 'Обучать - значит учить',
    wordTranslate: 'инструктирует',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4e6',
    group: 0,
    page: 3,
    word: 'issue',
    image: 'files/04_0071.jpg',
    audio: 'files/04_0071.mp3',
    audioMeaning: 'files/04_0071_meaning.mp3',
    audioExample: 'files/04_0071_example.mp3',
    textMeaning: 'An <i>issue</i> is an important topic.',
    textExample: 'The men spoke about <b>issues</b> that were important to the people.',
    transcription: '[íʃuː]',
    textExampleTranslate: 'Мужчины говорили о проблемах, которые были важны для людей',
    textMeaningTranslate: 'Проблема - важная тема',
    wordTranslate: 'проблема',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4e7',
    group: 0,
    page: 3,
    word: 'none',
    image: 'files/04_0072.jpg',
    audio: 'files/04_0072.mp3',
    audioMeaning: 'files/04_0072_meaning.mp3',
    audioExample: 'files/04_0072_example.mp3',
    textMeaning: '<i>None</i> means not any of something.',
    textExample: 'He spent all his money. There is <b>none</b> left.',
    transcription: '[nʌn]',
    textExampleTranslate: 'Он потратил все свои деньги. Там ничего не осталось',
    textMeaningTranslate: 'Никто не означает не что-то',
    wordTranslate: 'никто',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4e8',
    group: 0,
    page: 3,
    word: 'patient',
    image: 'files/04_0073.jpg',
    audio: 'files/04_0073.mp3',
    audioMeaning: 'files/04_0073_meaning.mp3',
    audioExample: 'files/04_0073_example.mp3',
    textMeaning: 'If people are <i>patient</i>, they don’t become angry or upset easily.',
    textExample: 'I had to be <b>patient</b> and wait until 5 o’clock to leave.',
    transcription: '[péiʃənt]',
    textExampleTranslate: 'Я должен был быть терпеливым и ждать, пока 5 часов, чтобы уйти',
    textMeaningTranslate: 'Если люди терпеливы, они не сердятся и не расстраиваются',
    wordTranslate: 'пациент',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4e9',
    group: 0,
    page: 3,
    word: 'positive',
    image: 'files/04_0074.jpg',
    audio: 'files/04_0074.mp3',
    audioMeaning: 'files/04_0074_meaning.mp3',
    audioExample: 'files/04_0074_example.mp3',
    textMeaning: 'If something is <i>positive</i>, it is good.',
    textExample: 'She has a <b>positive</b> future ahead of her after finishing college.',
    transcription: '[pɑ́zətiv]',
    textExampleTranslate: 'У нее впереди хорошее будущее после окончания колледжа',
    textMeaningTranslate: 'Если что-то положительное, это хорошо',
    wordTranslate: 'позитивный',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ea',
    group: 0,
    page: 3,
    word: 'punish',
    image: 'files/04_0075.jpg',
    audio: 'files/04_0075.mp3',
    audioMeaning: 'files/04_0075_meaning.mp3',
    audioExample: 'files/04_0075_example.mp3',
    textMeaning: 'To <i>punish</i> means to make someone suffer for breaking the rules or laws.',
    textExample: 'To <b>punish</b> me, my teacher had me stand in the corner.',
    transcription: '[pʌ́niʃ]',
    textExampleTranslate: 'Чтобы наказать меня, мой учитель заставил меня встать в углу',
    textMeaningTranslate: 'Наказать значит заставить кого-то страдать за нарушение правил или законов',
    wordTranslate: 'наказать',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4eb',
    group: 0,
    page: 3,
    word: 'represent',
    image: 'files/04_0076.jpg',
    audio: 'files/04_0076.mp3',
    audioMeaning: 'files/04_0076_meaning.mp3',
    audioExample: 'files/04_0076_example.mp3',
    textMeaning: 'To <i>represent</i> is to speak or act for a person or group.',
    textExample: 'My lawyer will <b>represent</b> me in court.',
    transcription: '[rèprizént]',
    textExampleTranslate: 'Мой адвокат будет представлять меня в суде',
    textMeaningTranslate: 'Представлять - значит говорить или действовать от лица или группы',
    wordTranslate: 'представлять',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ec',
    group: 0,
    page: 3,
    word: 'shake',
    image: 'files/04_0077.jpg',
    audio: 'files/04_0077.mp3',
    audioMeaning: 'files/04_0077_meaning.mp3',
    audioExample: 'files/04_0077_example.mp3',
    textMeaning: 'To <i>shake</i> is to move back and forth or up and down quickly.',
    textExample: 'When people <b>shake</b> hands, it usually means they agree.',
    transcription: '[ʃeik]',
    textExampleTranslate: 'Когда люди пожимают друг другу руки, это обычно означает, что они согласны',
    textMeaningTranslate: 'Трясти - значит быстро двигаться вперед-назад или вверх-вниз',
    wordTranslate: 'трясти',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ed',
    group: 0,
    page: 3,
    word: 'spread',
    image: 'files/04_0078.jpg',
    audio: 'files/04_0078.mp3',
    audioMeaning: 'files/04_0078_meaning.mp3',
    audioExample: 'files/04_0078_example.mp3',
    textMeaning: 'To <i>spread</i> is to move out to cover a larger area.',
    textExample: 'I like to <b>spread</b> butter on my toast.',
    transcription: '[spred]',
    textExampleTranslate: 'Мне нравится разливать масло по моему тосту',
    textMeaningTranslate: 'Распространение означает выход на большую площадь',
    wordTranslate: 'распространение',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ee',
    group: 0,
    page: 3,
    word: 'stroll',
    image: 'files/04_0079.jpg',
    audio: 'files/04_0079.mp3',
    audioMeaning: 'files/04_0079_meaning.mp3',
    audioExample: 'files/04_0079_example.mp3',
    textMeaning: 'To <i>stroll</i> means to walk slowly and calmly.',
    textExample: 'My dog and I <b>strolled</b> through the park today.',
    transcription: '[stroul]',
    textExampleTranslate: 'Сегодня мы с собакой прогулялись по парку',
    textMeaningTranslate: 'Гулять значит ходить медленно и спокойно',
    wordTranslate: 'прогулка',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ef',
    group: 0,
    page: 3,
    word: 'village',
    image: 'files/04_0080.jpg',
    audio: 'files/04_0080.mp3',
    audioMeaning: 'files/04_0080_meaning.mp3',
    audioExample: 'files/04_0080_example.mp3',
    textMeaning: 'A <i>village</i> is a very small town.',
    textExample: 'There are only a few houses in my <b>village</b>.',
    transcription: '[vílidʒ]',
    textExampleTranslate: 'В моей деревне всего несколько домов',
    textMeaningTranslate: 'Деревня очень маленький город',
    wordTranslate: 'деревня',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4f0',
    group: 0,
    page: 4,
    word: 'active',
    image: 'files/05_0081.jpg',
    audio: 'files/05_0081.mp3',
    audioMeaning: 'files/05_0081_meaning.mp3',
    audioExample: 'files/05_0081_example.mp3',
    textMeaning: 'When someone is <i>active</i>, they move a lot or have a lot of things to do.',
    textExample: 'It is important to be <b>active</b> and not sit around all the time.',
    transcription: '[ǽktiv]',
    textExampleTranslate: 'Важно быть активным, а не сидеть без дела все время',
    textMeaningTranslate: 'Когда кто-то активен, он много двигается или у него много дел',
    wordTranslate: 'активный',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4f1',
    group: 0,
    page: 4,
    word: 'adult',
    image: 'files/05_0082.jpg',
    audio: 'files/05_0082.mp3',
    audioMeaning: 'files/05_0082_meaning.mp3',
    audioExample: 'files/05_0082_example.mp3',
    textMeaning: 'An <i>adult</i> is a person who is more than 18 years old.',
    textExample: 'My mom and dad are <b>adults</b>.',
    transcription: '[ədΛlt]',
    textExampleTranslate: 'Мои мама и папа взрослые',
    textMeaningTranslate: 'Взрослый - это человек старше 18 лет',
    wordTranslate: 'взрослый',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4f2',
    group: 0,
    page: 4,
    word: 'balance',
    image: 'files/05_0085.jpg',
    audio: 'files/05_0085.mp3',
    audioMeaning: 'files/05_0085_meaning.mp3',
    audioExample: 'files/05_0085_example.mp3',
    textMeaning: '<i>Balance</i> is when two or more things are equal.',
    textExample: 'A good <b>balance</b> between work and fun helps keep you healthy.',
    transcription: '[bǽləns]',
    textExampleTranslate: 'Хороший баланс между работой и весельем помогает поддерживать здоровье',
    textMeaningTranslate: 'Баланс - это когда две или более вещи равны',
    wordTranslate: 'баланс',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4f3',
    group: 0,
    page: 4,
    word: 'bad',
    image: 'files/05_0084.jpg',
    audio: 'files/05_0084.mp3',
    audioMeaning: 'files/05_0084_meaning.mp3',
    audioExample: 'files/05_0084_example.mp3',
    textMeaning: 'When something is <i>bad</i>, it is not good.',
    textExample: 'She is unhappy because she had a <b>bad</b> day.',
    transcription: '[bæd]',
    textExampleTranslate: 'Она несчастна, потому что у нее был плохой день',
    textMeaningTranslate: 'Когда что-то плохо, это не хорошо',
    wordTranslate: 'плохой',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4f4',
    group: 0,
    page: 4,
    word: 'age',
    image: 'files/05_0083.jpg',
    audio: 'files/05_0083.mp3',
    audioMeaning: 'files/05_0083_meaning.mp3',
    audioExample: 'files/05_0083_example.mp3',
    textMeaning: '<i>Age</i> is how many years someone has lived.',
    textExample: 'She died at the <b>age</b> of 80.',
    transcription: '[eidʒ]',
    textExampleTranslate: 'Она умерла в возрасте 80 лет',
    textMeaningTranslate: 'Возраст - это сколько лет кто-то прожил',
    wordTranslate: 'возраст',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4f5',
    group: 0,
    page: 4,
    word: 'bike',
    image: 'files/05_0086.jpg',
    audio: 'files/05_0086.mp3',
    audioMeaning: 'files/05_0086_meaning.mp3',
    audioExample: 'files/05_0086_example.mp3',
    textMeaning: 'A <i>bike</i> is a vehicle with two wheels powered by a human.',
    textExample: 'He rides his <b>bike</b> to school every day.',
    transcription: '[baik]',
    textExampleTranslate: 'Он ездит на велосипеде в школу каждый день',
    textMeaningTranslate: 'Велосипед - это автомобиль с двумя колесами, приводимый в движение человеком',
    wordTranslate: 'велосипед',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4f6',
    group: 0,
    page: 4,
    word: 'choose',
    image: 'files/05_0087.jpg',
    audio: 'files/05_0087.mp3',
    audioMeaning: 'files/05_0087_meaning.mp3',
    audioExample: 'files/05_0087_example.mp3',
    textMeaning: 'To <i>choose</i> is to pick something or make a decision.',
    textExample: 'I have to <b>choose</b> between taking art classes and sports lessons.',
    transcription: '[tʃuːz]',
    textExampleTranslate: 'Мне нужно выбирать между занятиями искусством и занятиями спортом',
    textMeaningTranslate: 'Выбрать - это выбрать что-то или принять решение',
    wordTranslate: 'выбирать',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4f7',
    group: 0,
    page: 4,
    word: 'doctor',
    image: 'files/05_0088.jpg',
    audio: 'files/05_0088.mp3',
    audioMeaning: 'files/05_0088_meaning.mp3',
    audioExample: 'files/05_0088_example.mp3',
    textMeaning: 'A <i>doctor</i> is a person who studies medicine and helps sick people.',
    textExample: 'You should go to the <b>doctor</b> when you are sick.',
    transcription: '[dάktər]',
    textExampleTranslate: 'Вы должны идти к врачу, когда вы больны',
    textMeaningTranslate: 'Врач - это человек, который изучает медицину и помогает больным людям',
    wordTranslate: 'доктор',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4f8',
    group: 0,
    page: 4,
    word: 'during',
    image: 'files/05_0089.jpg',
    audio: 'files/05_0089.mp3',
    audioMeaning: 'files/05_0089_meaning.mp3',
    audioExample: 'files/05_0089_example.mp3',
    textMeaning: '<i>During</i> an event means while the event was happening.',
    textExample: 'Did you sleep <b>during</b> the movie?',
    transcription: '[djúəriŋ]',
    textExampleTranslate: 'Ты спал во время фильма?',
    textMeaningTranslate: 'Во время события означает, что событие происходило',
    wordTranslate: 'в течение',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4f9',
    group: 0,
    page: 4,
    word: 'football',
    image: 'files/05_0090.jpg',
    audio: 'files/05_0090.mp3',
    audioMeaning: 'files/05_0090_meaning.mp3',
    audioExample: 'files/05_0090_example.mp3',
    textMeaning: '<i>Football</i> is a sport with eleven members and an oval-shaped ball.',
    textExample: '<b>Football</b> is a popular sport in the United States.',
    transcription: '[fʊtbɒːl]',
    textExampleTranslate: 'Футбол - популярный вид спорта в Соединенных Штатах',
    textMeaningTranslate: 'Футбол - это спорт с одиннадцатью членами и мячом овальной формы',
    wordTranslate: 'футбол',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4fa',
    group: 0,
    page: 4,
    word: 'fun',
    image: 'files/05_0091.jpg',
    audio: 'files/05_0091.mp3',
    audioMeaning: 'files/05_0091_meaning.mp3',
    audioExample: 'files/05_0091_example.mp3',
    textMeaning: 'When something is <i>fun</i>, it is enjoyable.',
    textExample: 'We had a <b>fun</b> time at the birthday party.',
    transcription: '[fʌn]',
    textExampleTranslate: 'Мы весело провели время на вечеринке по случаю дня рождения',
    textMeaningTranslate: 'Когда что-то весело, это приятно',
    wordTranslate: 'веселье',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4fb',
    group: 0,
    page: 4,
    word: 'game',
    image: 'files/05_0092.jpg',
    audio: 'files/05_0092.mp3',
    audioMeaning: 'files/05_0092_meaning.mp3',
    audioExample: 'files/05_0092_example.mp3',
    textMeaning: 'A <i>game</i> is an activity where people compete against each other.',
    textExample: 'Let’s play a board <b>game</b> tonight.',
    transcription: '[geim]',
    textExampleTranslate: 'Давай поиграем в настольную игру сегодня вечером',
    textMeaningTranslate: 'Игра - это игра, в которой люди соревнуются друг с другом',
    wordTranslate: 'игра',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4fc',
    group: 0,
    page: 4,
    word: 'heart',
    image: 'files/05_0093.jpg',
    audio: 'files/05_0093.mp3',
    audioMeaning: 'files/05_0093_meaning.mp3',
    audioExample: 'files/05_0093_example.mp3',
    textMeaning: 'A <i>heart</i> is an organ that keeps the body alive.',
    textExample: 'My <b>heart</b> beats fast when I am nervous.',
    transcription: '[hɑːrt]',
    textExampleTranslate: 'Мое сердце бьется быстро, когда я нервничаю',
    textMeaningTranslate: 'Сердце - это орган, который поддерживает жизнь тела',
    wordTranslate: 'сердце',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4fd',
    group: 0,
    page: 4,
    word: 'golf',
    image: 'files/05_0094.jpg',
    audio: 'files/05_0094.mp3',
    audioMeaning: 'files/05_0094_meaning.mp3',
    audioExample: 'files/05_0094_example.mp3',
    textMeaning: '<i>Golf</i> is a sport with clubs and a small white ball.',
    textExample: 'People play <b>golf</b> in nice weather.',
    transcription: '[galf]',
    textExampleTranslate: 'Люди играют в гольф в хорошую погоду',
    textMeaningTranslate: 'Гольф - это спорт с клюшками и маленьким белым шариком',
    wordTranslate: 'гольф',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4fe',
    group: 0,
    page: 4,
    word: 'increase',
    image: 'files/05_0095.jpg',
    audio: 'files/05_0095.mp3',
    audioMeaning: 'files/05_0095_meaning.mp3',
    audioExample: 'files/05_0095_example.mp3',
    textMeaning: 'To <i>increase</i> is to make something larger.',
    textExample: 'I will <b>increase</b> my score if I study for the test.',
    transcription: '[inkríːs]',
    textExampleTranslate: 'Я увеличу свой счет, если я буду готовиться к экзамену',
    textMeaningTranslate: 'Увеличить значит сделать что-то большее',
    wordTranslate: 'увеличение',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ff',
    group: 0,
    page: 4,
    word: 'life',
    image: 'files/05_0096.jpg',
    audio: 'files/05_0096.mp3',
    audioMeaning: 'files/05_0096_meaning.mp3',
    audioExample: 'files/05_0096_example.mp3',
    textMeaning: '<i>Life</i> is the time when a person is alive.',
    textExample: 'My grandfather had a long <b>life</b>.',
    transcription: '[laif]',
    textExampleTranslate: 'У моего деда была долгая жизнь',
    textMeaningTranslate: 'Жизнь - это время, когда человек жив',
    wordTranslate: 'жизнь',
  },
  {
    id: '5e9f5ee35eb9e72bc21af500',
    group: 0,
    page: 4,
    word: 'kilometer',
    image: 'files/05_0097.jpg',
    audio: 'files/05_0097.mp3',
    audioMeaning: 'files/05_0097_meaning.mp3',
    audioExample: 'files/05_0097_example.mp3',
    textMeaning: 'A <i>kilometer</i> is a unit of measurement that is 1,000 meters.',
    textExample: 'A marathon is 42.2 <b>kilometers</b>.',
    transcription: '[kilάmətər]',
    textExampleTranslate: 'Марафон 42,2 километра',
    textMeaningTranslate: 'Километр - это единица измерения, которая составляет 1000 метров',
    wordTranslate: 'километр',
  },
  {
    id: '5e9f5ee35eb9e72bc21af501',
    group: 0,
    page: 4,
    word: 'often',
    image: 'files/05_0098.jpg',
    audio: 'files/05_0098.mp3',
    audioMeaning: 'files/05_0098_meaning.mp3',
    audioExample: 'files/05_0098_example.mp3',
    textMeaning: '<i>Often</i> is when something happens many times.',
    textExample: 'He <b>often</b> goes to bed early during the week.',
    transcription: '[ɔ́ːfən]',
    textExampleTranslate: 'Он часто ложится спать рано в течение недели',
    textMeaningTranslate: 'Часто бывает, когда что-то случается много раз',
    wordTranslate: 'довольно часто',
  },
  {
    id: '5e9f5ee35eb9e72bc21af502',
    group: 0,
    page: 4,
    word: 'plenty',
    image: 'files/05_0099.jpg',
    audio: 'files/05_0099.mp3',
    audioMeaning: 'files/05_0099_meaning.mp3',
    audioExample: 'files/05_0099_example.mp3',
    textMeaning: 'If you have <i>plenty</i> of something, there is a lot of it.',
    textExample: 'We have <b>plenty</b> of fruit, so help yourself.',
    transcription: '[plenti]',
    textExampleTranslate: 'У нас много фруктов, так что помогите себе',
    textMeaningTranslate: 'Если у вас много чего-то, то этого много',
    wordTranslate: 'много',
  },
  {
    id: '5e9f5ee35eb9e72bc21af503',
    group: 0,
    page: 4,
    word: 'weight',
    image: 'files/05_0100.jpg',
    audio: 'files/05_0100.mp3',
    audioMeaning: 'files/05_0100_meaning.mp3',
    audioExample: 'files/05_0100_example.mp3',
    textMeaning: '<i>Weight</i> is how heavy something or someone is.',
    textExample: 'I gained <b>weight</b> because I ate a lot of pizza.',
    transcription: '[weit]',
    textExampleTranslate: 'Я набрал вес, потому что я ел много пиццы',
    textMeaningTranslate: 'Вес - это то, как тяжело что-то или кто-то',
    wordTranslate: 'вес',
  },
];
export { basicWords, wrongWords };
